version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    env_file:
      - ./server/.env
    volumes:
      - ./server:/server
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - "MYSQL_DATABASE=nutricam"
      - "MYSQL_USER=nutricam"
      - "MYSQL_PASSWORD=local@123"
      - "MYSQL_ROOT_PASSWORD=local@123"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 2s
      retries: 5
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - server
    restart: always
    ports:
      - 5001:80